// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bookings.sql

package db

import (
	"context"
	"time"
)

const createBooking = `-- name: CreateBooking :one
INSERT INTO bookings (task_id, client_id, tasker_id, agreed_rate, status)
VALUES ($1, $2, $3, $4, 'confirmed')
RETURNING id, task_id, client_id, tasker_id, agreed_rate, status, started_at, completed_at, created_at
`

type CreateBookingParams struct {
	TaskID     int64   `json:"task_id"`
	ClientID   int64   `json:"client_id"`
	TaskerID   int64   `json:"tasker_id"`
	AgreedRate float64 `json:"agreed_rate"`
}

func (q *Queries) CreateBooking(ctx context.Context, arg CreateBookingParams) (Booking, error) {
	row := q.db.QueryRow(ctx, createBooking,
		arg.TaskID,
		arg.ClientID,
		arg.TaskerID,
		arg.AgreedRate,
	)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.ClientID,
		&i.TaskerID,
		&i.AgreedRate,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getBooking = `-- name: GetBooking :one
SELECT id, task_id, client_id, tasker_id, agreed_rate, status, started_at, completed_at, created_at FROM bookings
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetBooking(ctx context.Context, id int64) (Booking, error) {
	row := q.db.QueryRow(ctx, getBooking, id)
	var i Booking
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.ClientID,
		&i.TaskerID,
		&i.AgreedRate,
		&i.Status,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getBookingWithRelations = `-- name: GetBookingWithRelations :one
SELECT
  bookings.id, bookings.task_id, bookings.client_id, bookings.tasker_id, bookings.agreed_rate, bookings.status, bookings.started_at, bookings.completed_at, bookings.created_at,
  tasks.id, tasks.client_id, tasks.category_id, tasks.title, tasks.description, tasks.location_address, tasks.location_lat, tasks.location_lng, tasks.budget_type, tasks.budget_amount, tasks.status, tasks.scheduled_at, tasks.created_at, tasks.updated_at,
  categories.id, categories.name, categories.icon_url, categories.description,
  tasker_profiles.id, tasker_profiles.user_id, tasker_profiles.bio, tasker_profiles.hourly_rate, tasker_profiles.years_experience, tasker_profiles.service_radius_km, tasker_profiles.is_available, tasker_profiles.avg_rating, tasker_profiles.total_reviews, tasker_profiles.created_at, tasker_profiles.updated_at,
  client.id, client.email, client.password_hash, client.full_name, client.phone, client.role, client.avatar_url, client.is_verified, client.background_check_passed, client.created_at, client.updated_at,
  tasker_user.id, tasker_user.email, tasker_user.password_hash, tasker_user.full_name, tasker_user.phone, tasker_user.role, tasker_user.avatar_url, tasker_user.is_verified, tasker_user.background_check_passed, tasker_user.created_at, tasker_user.updated_at
FROM bookings
JOIN tasks ON tasks.id = bookings.task_id
JOIN categories ON categories.id = tasks.category_id
JOIN tasker_profiles ON tasker_profiles.id = bookings.tasker_id
JOIN users AS client ON client.id = bookings.client_id
JOIN users AS tasker_user ON tasker_user.id = tasker_profiles.user_id
WHERE bookings.id = $1 LIMIT 1
`

type GetBookingWithRelationsRow struct {
	Booking       Booking       `json:"booking"`
	Task          Task          `json:"task"`
	Category      Category      `json:"category"`
	TaskerProfile TaskerProfile `json:"tasker_profile"`
	User          User          `json:"user"`
	User_2        User          `json:"user_2"`
}

// users is joined twice: once as the client who posted the task, once as the
// account behind the tasker profile. The aliases are what the assembled
// response's "client" and "tasker.user" fields are built from.
func (q *Queries) GetBookingWithRelations(ctx context.Context, id int64) (GetBookingWithRelationsRow, error) {
	row := q.db.QueryRow(ctx, getBookingWithRelations, id)
	var i GetBookingWithRelationsRow
	err := row.Scan(
		&i.Booking.ID,
		&i.Booking.TaskID,
		&i.Booking.ClientID,
		&i.Booking.TaskerID,
		&i.Booking.AgreedRate,
		&i.Booking.Status,
		&i.Booking.StartedAt,
		&i.Booking.CompletedAt,
		&i.Booking.CreatedAt,
		&i.Task.ID,
		&i.Task.ClientID,
		&i.Task.CategoryID,
		&i.Task.Title,
		&i.Task.Description,
		&i.Task.LocationAddress,
		&i.Task.LocationLat,
		&i.Task.LocationLng,
		&i.Task.BudgetType,
		&i.Task.BudgetAmount,
		&i.Task.Status,
		&i.Task.ScheduledAt,
		&i.Task.CreatedAt,
		&i.Task.UpdatedAt,
		&i.Category.ID,
		&i.Category.Name,
		&i.Category.IconUrl,
		&i.Category.Description,
		&i.TaskerProfile.ID,
		&i.TaskerProfile.UserID,
		&i.TaskerProfile.Bio,
		&i.TaskerProfile.HourlyRate,
		&i.TaskerProfile.YearsExperience,
		&i.TaskerProfile.ServiceRadiusKm,
		&i.TaskerProfile.IsAvailable,
		&i.TaskerProfile.AvgRating,
		&i.TaskerProfile.TotalReviews,
		&i.TaskerProfile.CreatedAt,
		&i.TaskerProfile.UpdatedAt,
		&i.User.ID,
		&i.User.Email,
		&i.User.PasswordHash,
		&i.User.FullName,
		&i.User.Phone,
		&i.User.Role,
		&i.User.AvatarUrl,
		&i.User.IsVerified,
		&i.User.BackgroundCheckPassed,
		&i.User.CreatedAt,
		&i.User.UpdatedAt,
		&i.User_2.ID,
		&i.User_2.Email,
		&i.User_2.PasswordHash,
		&i.User_2.FullName,
		&i.User_2.Phone,
		&i.User_2.Role,
		&i.User_2.AvatarUrl,
		&i.User_2.IsVerified,
		&i.User_2.BackgroundCheckPassed,
		&i.User_2.CreatedAt,
		&i.User_2.UpdatedAt,
	)
	return i, err
}

const listBookingsByTasker = `-- name: ListBookingsByTasker :many
SELECT
  bookings.id, bookings.task_id, bookings.client_id, bookings.tasker_id, bookings.agreed_rate, bookings.status, bookings.started_at, bookings.completed_at, bookings.created_at,
  tasks.id, tasks.client_id, tasks.category_id, tasks.title, tasks.description, tasks.location_address, tasks.location_lat, tasks.location_lng, tasks.budget_type, tasks.budget_amount, tasks.status, tasks.scheduled_at, tasks.created_at, tasks.updated_at,
  categories.id, categories.name, categories.icon_url, categories.description,
  tasker_profiles.id, tasker_profiles.user_id, tasker_profiles.bio, tasker_profiles.hourly_rate, tasker_profiles.years_experience, tasker_profiles.service_radius_km, tasker_profiles.is_available, tasker_profiles.avg_rating, tasker_profiles.total_reviews, tasker_profiles.created_at, tasker_profiles.updated_at,
  client.id, client.email, client.password_hash, client.full_name, client.phone, client.role, client.avatar_url, client.is_verified, client.background_check_passed, client.created_at, client.updated_at,
  tasker_user.id, tasker_user.email, tasker_user.password_hash, tasker_user.full_name, tasker_user.phone, tasker_user.role, tasker_user.avatar_url, tasker_user.is_verified, tasker_user.background_check_passed, tasker_user.created_at, tasker_user.updated_at
FROM bookings
JOIN tasks ON tasks.id = bookings.task_id
JOIN categories ON categories.id = tasks.category_id
JOIN tasker_profiles ON tasker_profiles.id = bookings.tasker_id
JOIN users AS client ON client.id = bookings.client_id
JOIN users AS tasker_user ON tasker_user.id = tasker_profiles.user_id
WHERE bookings.tasker_id = $1
ORDER BY bookings.created_at DESC
`

type ListBookingsByTaskerRow struct {
	Booking       Booking       `json:"booking"`
	Task          Task          `json:"task"`
	Category      Category      `json:"category"`
	TaskerProfile TaskerProfile `json:"tasker_profile"`
	User          User          `json:"user"`
	User_2        User          `json:"user_2"`
}

func (q *Queries) ListBookingsByTasker(ctx context.Context, taskerID int64) ([]ListBookingsByTaskerRow, error) {
	rows, err := q.db.Query(ctx, listBookingsByTasker, taskerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBookingsByTaskerRow{}
	for rows.Next() {
		var i ListBookingsByTaskerRow
		if err := rows.Scan(
			&i.Booking.ID,
			&i.Booking.TaskID,
			&i.Booking.ClientID,
			&i.Booking.TaskerID,
			&i.Booking.AgreedRate,
			&i.Booking.Status,
			&i.Booking.StartedAt,
			&i.Booking.CompletedAt,
			&i.Booking.CreatedAt,
			&i.Task.ID,
			&i.Task.ClientID,
			&i.Task.CategoryID,
			&i.Task.Title,
			&i.Task.Description,
			&i.Task.LocationAddress,
			&i.Task.LocationLat,
			&i.Task.LocationLng,
			&i.Task.BudgetType,
			&i.Task.BudgetAmount,
			&i.Task.Status,
			&i.Task.ScheduledAt,
			&i.Task.CreatedAt,
			&i.Task.UpdatedAt,
			&i.Category.ID,
			&i.Category.Name,
			&i.Category.IconUrl,
			&i.Category.Description,
			&i.TaskerProfile.ID,
			&i.TaskerProfile.UserID,
			&i.TaskerProfile.Bio,
			&i.TaskerProfile.HourlyRate,
			&i.TaskerProfile.YearsExperience,
			&i.TaskerProfile.ServiceRadiusKm,
			&i.TaskerProfile.IsAvailable,
			&i.TaskerProfile.AvgRating,
			&i.TaskerProfile.TotalReviews,
			&i.TaskerProfile.CreatedAt,
			&i.TaskerProfile.UpdatedAt,
			&i.User.ID,
			&i.User.Email,
			&i.User.PasswordHash,
			&i.User.FullName,
			&i.User.Phone,
			&i.User.Role,
			&i.User.AvatarUrl,
			&i.User.IsVerified,
			&i.User.BackgroundCheckPassed,
			&i.User.CreatedAt,
			&i.User.UpdatedAt,
			&i.User_2.ID,
			&i.User_2.Email,
			&i.User_2.PasswordHash,
			&i.User_2.FullName,
			&i.User_2.Phone,
			&i.User_2.Role,
			&i.User_2.AvatarUrl,
			&i.User_2.IsVerified,
			&i.User_2.BackgroundCheckPassed,
			&i.User_2.CreatedAt,
			&i.User_2.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBookingsForUser = `-- name: ListBookingsForUser :many
SELECT
  bookings.id, bookings.task_id, bookings.client_id, bookings.tasker_id, bookings.agreed_rate, bookings.status, bookings.started_at, bookings.completed_at, bookings.created_at,
  tasks.id, tasks.client_id, tasks.category_id, tasks.title, tasks.description, tasks.location_address, tasks.location_lat, tasks.location_lng, tasks.budget_type, tasks.budget_amount, tasks.status, tasks.scheduled_at, tasks.created_at, tasks.updated_at,
  categories.id, categories.name, categories.icon_url, categories.description,
  tasker_profiles.id, tasker_profiles.user_id, tasker_profiles.bio, tasker_profiles.hourly_rate, tasker_profiles.years_experience, tasker_profiles.service_radius_km, tasker_profiles.is_available, tasker_profiles.avg_rating, tasker_profiles.total_reviews, tasker_profiles.created_at, tasker_profiles.updated_at,
  client.id, client.email, client.password_hash, client.full_name, client.phone, client.role, client.avatar_url, client.is_verified, client.background_check_passed, client.created_at, client.updated_at,
  tasker_user.id, tasker_user.email, tasker_user.password_hash, tasker_user.full_name, tasker_user.phone, tasker_user.role, tasker_user.avatar_url, tasker_user.is_verified, tasker_user.background_check_passed, tasker_user.created_at, tasker_user.updated_at
FROM bookings
JOIN tasks ON tasks.id = bookings.task_id
JOIN categories ON categories.id = tasks.category_id
JOIN tasker_profiles ON tasker_profiles.id = bookings.tasker_id
JOIN users AS client ON client.id = bookings.client_id
JOIN users AS tasker_user ON tasker_user.id = tasker_profiles.user_id
WHERE bookings.client_id = $1
   OR ($2::bigint IS NOT NULL AND bookings.tasker_id = $2)
ORDER BY bookings.created_at DESC
`

type ListBookingsForUserParams struct {
	ClientID int64  `json:"client_id"`
	TaskerID *int64 `json:"tasker_id"`
}

type ListBookingsForUserRow struct {
	Booking       Booking       `json:"booking"`
	Task          Task          `json:"task"`
	Category      Category      `json:"category"`
	TaskerProfile TaskerProfile `json:"tasker_profile"`
	User          User          `json:"user"`
	User_2        User          `json:"user_2"`
}

// Everything the caller takes part in, on either side. tasker_id is NULL for a
// caller with no tasker profile, which drops that half of the predicate.
func (q *Queries) ListBookingsForUser(ctx context.Context, arg ListBookingsForUserParams) ([]ListBookingsForUserRow, error) {
	rows, err := q.db.Query(ctx, listBookingsForUser, arg.ClientID, arg.TaskerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBookingsForUserRow{}
	for rows.Next() {
		var i ListBookingsForUserRow
		if err := rows.Scan(
			&i.Booking.ID,
			&i.Booking.TaskID,
			&i.Booking.ClientID,
			&i.Booking.TaskerID,
			&i.Booking.AgreedRate,
			&i.Booking.Status,
			&i.Booking.StartedAt,
			&i.Booking.CompletedAt,
			&i.Booking.CreatedAt,
			&i.Task.ID,
			&i.Task.ClientID,
			&i.Task.CategoryID,
			&i.Task.Title,
			&i.Task.Description,
			&i.Task.LocationAddress,
			&i.Task.LocationLat,
			&i.Task.LocationLng,
			&i.Task.BudgetType,
			&i.Task.BudgetAmount,
			&i.Task.Status,
			&i.Task.ScheduledAt,
			&i.Task.CreatedAt,
			&i.Task.UpdatedAt,
			&i.Category.ID,
			&i.Category.Name,
			&i.Category.IconUrl,
			&i.Category.Description,
			&i.TaskerProfile.ID,
			&i.TaskerProfile.UserID,
			&i.TaskerProfile.Bio,
			&i.TaskerProfile.HourlyRate,
			&i.TaskerProfile.YearsExperience,
			&i.TaskerProfile.ServiceRadiusKm,
			&i.TaskerProfile.IsAvailable,
			&i.TaskerProfile.AvgRating,
			&i.TaskerProfile.TotalReviews,
			&i.TaskerProfile.CreatedAt,
			&i.TaskerProfile.UpdatedAt,
			&i.User.ID,
			&i.User.Email,
			&i.User.PasswordHash,
			&i.User.FullName,
			&i.User.Phone,
			&i.User.Role,
			&i.User.AvatarUrl,
			&i.User.IsVerified,
			&i.User.BackgroundCheckPassed,
			&i.User.CreatedAt,
			&i.User.UpdatedAt,
			&i.User_2.ID,
			&i.User_2.Email,
			&i.User_2.PasswordHash,
			&i.User_2.FullName,
			&i.User_2.Phone,
			&i.User_2.Role,
			&i.User_2.AvatarUrl,
			&i.User_2.IsVerified,
			&i.User_2.BackgroundCheckPassed,
			&i.User_2.CreatedAt,
			&i.User_2.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBookingStatus = `-- name: UpdateBookingStatus :exec
UPDATE bookings
SET
  status = $1,
  started_at = COALESCE($2, started_at),
  completed_at = COALESCE($3, completed_at)
WHERE id = $4
`

type UpdateBookingStatusParams struct {
	Status      string     `json:"status"`
	StartedAt   *time.Time `json:"started_at"`
	CompletedAt *time.Time `json:"completed_at"`
	ID          int64      `json:"id"`
}

// started_at/completed_at are passed as NULL for the transitions that do not
// set them, and COALESCE keeps whatever an earlier transition already stamped.
func (q *Queries) UpdateBookingStatus(ctx context.Context, arg UpdateBookingStatusParams) error {
	_, err := q.db.Exec(ctx, updateBookingStatus,
		arg.Status,
		arg.StartedAt,
		arg.CompletedAt,
		arg.ID,
	)
	return err
}
