// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: messages.sql

package db

import (
	"context"
)

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (booking_id, sender_id, content)
VALUES ($1, $2, $3)
RETURNING id, booking_id, sender_id, content, is_read, created_at
`

type CreateMessageParams struct {
	BookingID int64  `json:"booking_id"`
	SenderID  int64  `json:"sender_id"`
	Content   string `json:"content"`
}

func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, createMessage, arg.BookingID, arg.SenderID, arg.Content)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.SenderID,
		&i.Content,
		&i.IsRead,
		&i.CreatedAt,
	)
	return i, err
}

const getMessageWithSender = `-- name: GetMessageWithSender :one
SELECT messages.id, messages.booking_id, messages.sender_id, messages.content, messages.is_read, messages.created_at, users.id, users.email, users.password_hash, users.full_name, users.phone, users.role, users.avatar_url, users.is_verified, users.background_check_passed, users.created_at, users.updated_at
FROM messages
JOIN users ON users.id = messages.sender_id
WHERE messages.id = $1 LIMIT 1
`

type GetMessageWithSenderRow struct {
	Message Message `json:"message"`
	User    User    `json:"user"`
}

func (q *Queries) GetMessageWithSender(ctx context.Context, id int64) (GetMessageWithSenderRow, error) {
	row := q.db.QueryRow(ctx, getMessageWithSender, id)
	var i GetMessageWithSenderRow
	err := row.Scan(
		&i.Message.ID,
		&i.Message.BookingID,
		&i.Message.SenderID,
		&i.Message.Content,
		&i.Message.IsRead,
		&i.Message.CreatedAt,
		&i.User.ID,
		&i.User.Email,
		&i.User.PasswordHash,
		&i.User.FullName,
		&i.User.Phone,
		&i.User.Role,
		&i.User.AvatarUrl,
		&i.User.IsVerified,
		&i.User.BackgroundCheckPassed,
		&i.User.CreatedAt,
		&i.User.UpdatedAt,
	)
	return i, err
}

const listMessagesByBooking = `-- name: ListMessagesByBooking :many
SELECT messages.id, messages.booking_id, messages.sender_id, messages.content, messages.is_read, messages.created_at, users.id, users.email, users.password_hash, users.full_name, users.phone, users.role, users.avatar_url, users.is_verified, users.background_check_passed, users.created_at, users.updated_at
FROM messages
JOIN users ON users.id = messages.sender_id
WHERE messages.booking_id = $1
ORDER BY messages.created_at ASC
`

type ListMessagesByBookingRow struct {
	Message Message `json:"message"`
	User    User    `json:"user"`
}

func (q *Queries) ListMessagesByBooking(ctx context.Context, bookingID int64) ([]ListMessagesByBookingRow, error) {
	rows, err := q.db.Query(ctx, listMessagesByBooking, bookingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMessagesByBookingRow{}
	for rows.Next() {
		var i ListMessagesByBookingRow
		if err := rows.Scan(
			&i.Message.ID,
			&i.Message.BookingID,
			&i.Message.SenderID,
			&i.Message.Content,
			&i.Message.IsRead,
			&i.Message.CreatedAt,
			&i.User.ID,
			&i.User.Email,
			&i.User.PasswordHash,
			&i.User.FullName,
			&i.User.Phone,
			&i.User.Role,
			&i.User.AvatarUrl,
			&i.User.IsVerified,
			&i.User.BackgroundCheckPassed,
			&i.User.CreatedAt,
			&i.User.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markMessagesRead = `-- name: MarkMessagesRead :exec
UPDATE messages
SET is_read = TRUE
WHERE booking_id = $1 AND sender_id <> $2 AND is_read = FALSE
`

type MarkMessagesReadParams struct {
	BookingID int64 `json:"booking_id"`
	SenderID  int64 `json:"sender_id"`
}

// Reading the thread marks everything the caller did not write as seen.
func (q *Queries) MarkMessagesRead(ctx context.Context, arg MarkMessagesReadParams) error {
	_, err := q.db.Exec(ctx, markMessagesRead, arg.BookingID, arg.SenderID)
	return err
}
