// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"time"
)

type Booking struct {
	ID          int64      `json:"id"`
	TaskID      int64      `json:"task_id"`
	ClientID    int64      `json:"client_id"`
	TaskerID    int64      `json:"tasker_id"`
	AgreedRate  float64    `json:"agreed_rate"`
	Status      string     `json:"status"`
	StartedAt   *time.Time `json:"started_at"`
	CompletedAt *time.Time `json:"completed_at"`
	CreatedAt   time.Time  `json:"created_at"`
}

type Category struct {
	ID          int64  `json:"id"`
	Name        string `json:"name"`
	IconUrl     string `json:"icon_url"`
	Description string `json:"description"`
}

type Message struct {
	ID        int64     `json:"id"`
	BookingID int64     `json:"booking_id"`
	SenderID  int64     `json:"sender_id"`
	Content   string    `json:"content"`
	IsRead    bool      `json:"is_read"`
	CreatedAt time.Time `json:"created_at"`
}

type Payment struct {
	ID                    int64     `json:"id"`
	BookingID             int64     `json:"booking_id"`
	ClientID              int64     `json:"client_id"`
	TaskerID              int64     `json:"tasker_id"`
	Amount                float64   `json:"amount"`
	TipAmount             float64   `json:"tip_amount"`
	StripePaymentIntentID string    `json:"stripe_payment_intent_id"`
	Status                string    `json:"status"`
	CreatedAt             time.Time `json:"created_at"`
}

type Review struct {
	ID         int64     `json:"id"`
	BookingID  int64     `json:"booking_id"`
	ReviewerID int64     `json:"reviewer_id"`
	RevieweeID int64     `json:"reviewee_id"`
	Rating     int32     `json:"rating"`
	Comment    string    `json:"comment"`
	CreatedAt  time.Time `json:"created_at"`
}

type Task struct {
	ID              int64      `json:"id"`
	ClientID        int64      `json:"client_id"`
	CategoryID      int64      `json:"category_id"`
	Title           string     `json:"title"`
	Description     string     `json:"description"`
	LocationAddress string     `json:"location_address"`
	LocationLat     float64    `json:"location_lat"`
	LocationLng     float64    `json:"location_lng"`
	BudgetType      string     `json:"budget_type"`
	BudgetAmount    float64    `json:"budget_amount"`
	Status          string     `json:"status"`
	ScheduledAt     *time.Time `json:"scheduled_at"`
	CreatedAt       time.Time  `json:"created_at"`
	UpdatedAt       time.Time  `json:"updated_at"`
}

type TaskApplication struct {
	ID           int64     `json:"id"`
	TaskID       int64     `json:"task_id"`
	TaskerID     int64     `json:"tasker_id"`
	ProposedRate float64   `json:"proposed_rate"`
	CoverNote    string    `json:"cover_note"`
	Status       string    `json:"status"`
	CreatedAt    time.Time `json:"created_at"`
}

type TaskerAvailability struct {
	ID        int64  `json:"id"`
	TaskerID  int64  `json:"tasker_id"`
	DayOfWeek int32  `json:"day_of_week"`
	StartTime string `json:"start_time"`
	EndTime   string `json:"end_time"`
}

type TaskerProfile struct {
	ID              int64     `json:"id"`
	UserID          int64     `json:"user_id"`
	Bio             string    `json:"bio"`
	HourlyRate      float64   `json:"hourly_rate"`
	YearsExperience int32     `json:"years_experience"`
	ServiceRadiusKm float64   `json:"service_radius_km"`
	IsAvailable     bool      `json:"is_available"`
	AvgRating       float64   `json:"avg_rating"`
	TotalReviews    int32     `json:"total_reviews"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
}

type TaskerSkill struct {
	ID         int64 `json:"id"`
	TaskerID   int64 `json:"tasker_id"`
	CategoryID int64 `json:"category_id"`
}

type User struct {
	ID                    int64     `json:"id"`
	Email                 string    `json:"email"`
	PasswordHash          string    `json:"password_hash"`
	FullName              string    `json:"full_name"`
	Phone                 string    `json:"phone"`
	Role                  string    `json:"role"`
	AvatarUrl             string    `json:"avatar_url"`
	IsVerified            bool      `json:"is_verified"`
	BackgroundCheckPassed bool      `json:"background_check_passed"`
	CreatedAt             time.Time `json:"created_at"`
	UpdatedAt             time.Time `json:"updated_at"`
}
