// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payments.sql

package db

import (
	"context"
)

const addPaymentTip = `-- name: AddPaymentTip :one
UPDATE payments
SET tip_amount = tip_amount + $2
WHERE booking_id = $1
RETURNING id, booking_id, client_id, tasker_id, amount, tip_amount, stripe_payment_intent_id, status, created_at
`

type AddPaymentTipParams struct {
	BookingID int64   `json:"booking_id"`
	TipAmount float64 `json:"tip_amount"`
}

func (q *Queries) AddPaymentTip(ctx context.Context, arg AddPaymentTipParams) (Payment, error) {
	row := q.db.QueryRow(ctx, addPaymentTip, arg.BookingID, arg.TipAmount)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.ClientID,
		&i.TaskerID,
		&i.Amount,
		&i.TipAmount,
		&i.StripePaymentIntentID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getPaymentByBooking = `-- name: GetPaymentByBooking :one
SELECT id, booking_id, client_id, tasker_id, amount, tip_amount, stripe_payment_intent_id, status, created_at FROM payments
WHERE booking_id = $1 LIMIT 1
`

func (q *Queries) GetPaymentByBooking(ctx context.Context, bookingID int64) (Payment, error) {
	row := q.db.QueryRow(ctx, getPaymentByBooking, bookingID)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.ClientID,
		&i.TaskerID,
		&i.Amount,
		&i.TipAmount,
		&i.StripePaymentIntentID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const settlePaymentByCheckoutID = `-- name: SettlePaymentByCheckoutID :exec
UPDATE payments
SET status = $2
WHERE stripe_payment_intent_id = $1
`

type SettlePaymentByCheckoutIDParams struct {
	StripePaymentIntentID string `json:"stripe_payment_intent_id"`
	Status                string `json:"status"`
}

// The provider callback knows only the checkout id it echoes back.
func (q *Queries) SettlePaymentByCheckoutID(ctx context.Context, arg SettlePaymentByCheckoutIDParams) error {
	_, err := q.db.Exec(ctx, settlePaymentByCheckoutID, arg.StripePaymentIntentID, arg.Status)
	return err
}

const updatePaymentStatus = `-- name: UpdatePaymentStatus :one
UPDATE payments
SET status = $2
WHERE booking_id = $1
RETURNING id, booking_id, client_id, tasker_id, amount, tip_amount, stripe_payment_intent_id, status, created_at
`

type UpdatePaymentStatusParams struct {
	BookingID int64  `json:"booking_id"`
	Status    string `json:"status"`
}

func (q *Queries) UpdatePaymentStatus(ctx context.Context, arg UpdatePaymentStatusParams) (Payment, error) {
	row := q.db.QueryRow(ctx, updatePaymentStatus, arg.BookingID, arg.Status)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.ClientID,
		&i.TaskerID,
		&i.Amount,
		&i.TipAmount,
		&i.StripePaymentIntentID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const upsertPayment = `-- name: UpsertPayment :one
INSERT INTO payments (booking_id, client_id, tasker_id, amount, stripe_payment_intent_id, status)
VALUES ($1, $2, $3, $4, $5, 'pending')
ON CONFLICT (booking_id) DO UPDATE
SET
  client_id = EXCLUDED.client_id,
  tasker_id = EXCLUDED.tasker_id,
  amount = EXCLUDED.amount,
  stripe_payment_intent_id = EXCLUDED.stripe_payment_intent_id,
  status = 'pending'
RETURNING id, booking_id, client_id, tasker_id, amount, tip_amount, stripe_payment_intent_id, status, created_at
`

type UpsertPaymentParams struct {
	BookingID             int64   `json:"booking_id"`
	ClientID              int64   `json:"client_id"`
	TaskerID              int64   `json:"tasker_id"`
	Amount                float64 `json:"amount"`
	StripePaymentIntentID string  `json:"stripe_payment_intent_id"`
}

// One payment per booking (booking_id is UNIQUE), so re-initiating replaces the
// pending intent rather than accumulating rows. The tip is left alone: it is
// added separately and must survive a retried checkout.
func (q *Queries) UpsertPayment(ctx context.Context, arg UpsertPaymentParams) (Payment, error) {
	row := q.db.QueryRow(ctx, upsertPayment,
		arg.BookingID,
		arg.ClientID,
		arg.TaskerID,
		arg.Amount,
		arg.StripePaymentIntentID,
	)
	var i Payment
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.ClientID,
		&i.TaskerID,
		&i.Amount,
		&i.TipAmount,
		&i.StripePaymentIntentID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
