// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"
)

type Querier interface {
	AddPaymentTip(ctx context.Context, arg AddPaymentTipParams) (Payment, error)
	CountApplicationsByTaskAndTasker(ctx context.Context, arg CountApplicationsByTaskAndTaskerParams) (int64, error)
	CountReviewsByBookingAndReviewer(ctx context.Context, arg CountReviewsByBookingAndReviewerParams) (int64, error)
	CreateBooking(ctx context.Context, arg CreateBookingParams) (Booking, error)
	CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error)
	CreateReview(ctx context.Context, arg CreateReviewParams) (Review, error)
	CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error)
	CreateTaskApplication(ctx context.Context, arg CreateTaskApplicationParams) (TaskApplication, error)
	CreateTaskerAvailability(ctx context.Context, arg CreateTaskerAvailabilityParams) (TaskerAvailability, error)
	CreateTaskerProfile(ctx context.Context, arg CreateTaskerProfileParams) (TaskerProfile, error)
	CreateTaskerSkill(ctx context.Context, arg CreateTaskerSkillParams) (TaskerSkill, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteTaskerAvailability(ctx context.Context, taskerID int64) error
	DeleteTaskerSkills(ctx context.Context, taskerID int64) error
	GetApplicationWithTasker(ctx context.Context, id int64) (GetApplicationWithTaskerRow, error)
	GetBooking(ctx context.Context, id int64) (Booking, error)
	// users is joined twice: once as the client who posted the task, once as the
	// account behind the tasker profile. The aliases are what the assembled
	// response's "client" and "tasker.user" fields are built from.
	GetBookingWithRelations(ctx context.Context, id int64) (GetBookingWithRelationsRow, error)
	GetCategory(ctx context.Context, id int64) (Category, error)
	GetCategoryByName(ctx context.Context, name string) (Category, error)
	GetMessageWithSender(ctx context.Context, id int64) (GetMessageWithSenderRow, error)
	GetPaymentByBooking(ctx context.Context, bookingID int64) (Payment, error)
	GetReviewWithReviewer(ctx context.Context, id int64) (GetReviewWithReviewerRow, error)
	// Feeds the denormalised columns on tasker_profiles. COALESCE covers the
	// reviewee with no reviews yet, where AVG is NULL.
	GetRevieweeRatingStats(ctx context.Context, revieweeID int64) (GetRevieweeRatingStatsRow, error)
	GetTask(ctx context.Context, id int64) (Task, error)
	GetTaskApplication(ctx context.Context, arg GetTaskApplicationParams) (TaskApplication, error)
	GetTaskWithRelations(ctx context.Context, id int64) (GetTaskWithRelationsRow, error)
	GetTaskerProfile(ctx context.Context, id int64) (TaskerProfile, error)
	GetTaskerProfileByUserID(ctx context.Context, userID int64) (TaskerProfile, error)
	GetTaskerProfileWithUser(ctx context.Context, id int64) (GetTaskerProfileWithUserRow, error)
	GetTaskerProfileWithUserByUserID(ctx context.Context, userID int64) (GetTaskerProfileWithUserByUserIDRow, error)
	GetUser(ctx context.Context, id int64) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	// Batch form so a page of tasks costs one query for all their applications
	// rather than one per task.
	ListApplicationsByTaskIDs(ctx context.Context, taskIds []int64) ([]ListApplicationsByTaskIDsRow, error)
	ListApplicationsByTasker(ctx context.Context, taskerID int64) ([]ListApplicationsByTaskerRow, error)
	ListBookingsByTasker(ctx context.Context, taskerID int64) ([]ListBookingsByTaskerRow, error)
	// Everything the caller takes part in, on either side. tasker_id is NULL for a
	// caller with no tasker profile, which drops that half of the predicate.
	ListBookingsForUser(ctx context.Context, arg ListBookingsForUserParams) ([]ListBookingsForUserRow, error)
	ListCategories(ctx context.Context) ([]Category, error)
	ListMessagesByBooking(ctx context.Context, bookingID int64) ([]ListMessagesByBookingRow, error)
	// The marketplace feed taskers browse. As with ListTaskerProfiles, each filter
	// is skipped when its argument is NULL.
	ListOpenTasks(ctx context.Context, arg ListOpenTasksParams) ([]ListOpenTasksRow, error)
	ListReviewsByBooking(ctx context.Context, bookingID int64) ([]ListReviewsByBookingRow, error)
	ListReviewsByReviewee(ctx context.Context, revieweeID int64) ([]ListReviewsByRevieweeRow, error)
	ListTaskerAvailability(ctx context.Context, taskerID int64) ([]TaskerAvailability, error)
	ListTaskerAvailabilityByTaskerIDs(ctx context.Context, taskerIds []int64) ([]TaskerAvailability, error)
	// The directory listing. Every filter is optional: a NULL argument drops its
	// own clause, which is how one prepared statement covers what the handler used
	// to assemble by chaining query builders.
	//
	// The category filter is an EXISTS rather than a JOIN so a tasker holding
	// several skills still comes back as one row.
	ListTaskerProfiles(ctx context.Context, arg ListTaskerProfilesParams) ([]ListTaskerProfilesRow, error)
	ListTaskerSkills(ctx context.Context, taskerID int64) ([]ListTaskerSkillsRow, error)
	// Batch form for list endpoints: one query for the whole page of taskers
	// instead of one per row, which is what Preload was doing.
	ListTaskerSkillsByTaskerIDs(ctx context.Context, taskerIds []int64) ([]ListTaskerSkillsByTaskerIDsRow, error)
	ListTasksByClient(ctx context.Context, clientID int64) ([]ListTasksByClientRow, error)
	// Reading the thread marks everything the caller did not write as seen.
	MarkMessagesRead(ctx context.Context, arg MarkMessagesReadParams) error
	// Accepting one application closes the rest for that task in the same
	// transaction, so a client can never book two taskers for one job.
	RejectRivalApplications(ctx context.Context, arg RejectRivalApplicationsParams) error
	// The provider callback knows only the checkout id it echoes back.
	SettlePaymentByCheckoutID(ctx context.Context, arg SettlePaymentByCheckoutIDParams) error
	UpdateApplicationStatus(ctx context.Context, arg UpdateApplicationStatusParams) error
	// started_at/completed_at are passed as NULL for the transitions that do not
	// set them, and COALESCE keeps whatever an earlier transition already stamped.
	UpdateBookingStatus(ctx context.Context, arg UpdateBookingStatusParams) error
	UpdatePaymentStatus(ctx context.Context, arg UpdatePaymentStatusParams) (Payment, error)
	UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error)
	UpdateTaskStatus(ctx context.Context, arg UpdateTaskStatusParams) error
	// Partial update: the dashboard sends only the fields the tasker touched, and
	// a NULL here means "not supplied" rather than "set to zero".
	UpdateTaskerProfile(ctx context.Context, arg UpdateTaskerProfileParams) (TaskerProfile, error)
	// Refreshes the denormalised rating columns after a review lands. A no-op when
	// the reviewee is a client, who has no tasker profile -- hence :exec rather
	// than :one, which would report ErrNoRows for a perfectly normal case.
	UpdateTaskerRatingByUserID(ctx context.Context, arg UpdateTaskerRatingByUserIDParams) error
	// COALESCE rather than a blanket write: the profile form submits only the
	// fields it shows, and an absent key must leave the column alone instead of
	// blanking it.
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	// One payment per booking (booking_id is UNIQUE), so re-initiating replaces the
	// pending intent rather than accumulating rows. The tip is left alone: it is
	// added separately and must survive a retried checkout.
	UpsertPayment(ctx context.Context, arg UpsertPaymentParams) (Payment, error)
}

var _ Querier = (*Queries)(nil)
