// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reviews.sql

package db

import (
	"context"
)

const countReviewsByBookingAndReviewer = `-- name: CountReviewsByBookingAndReviewer :one
SELECT COUNT(*) FROM reviews
WHERE booking_id = $1 AND reviewer_id = $2
`

type CountReviewsByBookingAndReviewerParams struct {
	BookingID  int64 `json:"booking_id"`
	ReviewerID int64 `json:"reviewer_id"`
}

func (q *Queries) CountReviewsByBookingAndReviewer(ctx context.Context, arg CountReviewsByBookingAndReviewerParams) (int64, error) {
	row := q.db.QueryRow(ctx, countReviewsByBookingAndReviewer, arg.BookingID, arg.ReviewerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createReview = `-- name: CreateReview :one
INSERT INTO reviews (booking_id, reviewer_id, reviewee_id, rating, comment)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, booking_id, reviewer_id, reviewee_id, rating, comment, created_at
`

type CreateReviewParams struct {
	BookingID  int64  `json:"booking_id"`
	ReviewerID int64  `json:"reviewer_id"`
	RevieweeID int64  `json:"reviewee_id"`
	Rating     int32  `json:"rating"`
	Comment    string `json:"comment"`
}

func (q *Queries) CreateReview(ctx context.Context, arg CreateReviewParams) (Review, error) {
	row := q.db.QueryRow(ctx, createReview,
		arg.BookingID,
		arg.ReviewerID,
		arg.RevieweeID,
		arg.Rating,
		arg.Comment,
	)
	var i Review
	err := row.Scan(
		&i.ID,
		&i.BookingID,
		&i.ReviewerID,
		&i.RevieweeID,
		&i.Rating,
		&i.Comment,
		&i.CreatedAt,
	)
	return i, err
}

const getReviewWithReviewer = `-- name: GetReviewWithReviewer :one
SELECT reviews.id, reviews.booking_id, reviews.reviewer_id, reviews.reviewee_id, reviews.rating, reviews.comment, reviews.created_at, users.id, users.email, users.password_hash, users.full_name, users.phone, users.role, users.avatar_url, users.is_verified, users.background_check_passed, users.created_at, users.updated_at
FROM reviews
JOIN users ON users.id = reviews.reviewer_id
WHERE reviews.id = $1 LIMIT 1
`

type GetReviewWithReviewerRow struct {
	Review Review `json:"review"`
	User   User   `json:"user"`
}

func (q *Queries) GetReviewWithReviewer(ctx context.Context, id int64) (GetReviewWithReviewerRow, error) {
	row := q.db.QueryRow(ctx, getReviewWithReviewer, id)
	var i GetReviewWithReviewerRow
	err := row.Scan(
		&i.Review.ID,
		&i.Review.BookingID,
		&i.Review.ReviewerID,
		&i.Review.RevieweeID,
		&i.Review.Rating,
		&i.Review.Comment,
		&i.Review.CreatedAt,
		&i.User.ID,
		&i.User.Email,
		&i.User.PasswordHash,
		&i.User.FullName,
		&i.User.Phone,
		&i.User.Role,
		&i.User.AvatarUrl,
		&i.User.IsVerified,
		&i.User.BackgroundCheckPassed,
		&i.User.CreatedAt,
		&i.User.UpdatedAt,
	)
	return i, err
}

const getRevieweeRatingStats = `-- name: GetRevieweeRatingStats :one
SELECT
  COALESCE(AVG(rating), 0)::numeric AS average,
  COUNT(*)::int AS total
FROM reviews
WHERE reviewee_id = $1
`

type GetRevieweeRatingStatsRow struct {
	Average float64 `json:"average"`
	Total   int32   `json:"total"`
}

// Feeds the denormalised columns on tasker_profiles. COALESCE covers the
// reviewee with no reviews yet, where AVG is NULL.
func (q *Queries) GetRevieweeRatingStats(ctx context.Context, revieweeID int64) (GetRevieweeRatingStatsRow, error) {
	row := q.db.QueryRow(ctx, getRevieweeRatingStats, revieweeID)
	var i GetRevieweeRatingStatsRow
	err := row.Scan(&i.Average, &i.Total)
	return i, err
}

const listReviewsByBooking = `-- name: ListReviewsByBooking :many
SELECT reviews.id, reviews.booking_id, reviews.reviewer_id, reviews.reviewee_id, reviews.rating, reviews.comment, reviews.created_at, users.id, users.email, users.password_hash, users.full_name, users.phone, users.role, users.avatar_url, users.is_verified, users.background_check_passed, users.created_at, users.updated_at
FROM reviews
JOIN users ON users.id = reviews.reviewer_id
WHERE reviews.booking_id = $1
ORDER BY reviews.created_at DESC
`

type ListReviewsByBookingRow struct {
	Review Review `json:"review"`
	User   User   `json:"user"`
}

func (q *Queries) ListReviewsByBooking(ctx context.Context, bookingID int64) ([]ListReviewsByBookingRow, error) {
	rows, err := q.db.Query(ctx, listReviewsByBooking, bookingID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReviewsByBookingRow{}
	for rows.Next() {
		var i ListReviewsByBookingRow
		if err := rows.Scan(
			&i.Review.ID,
			&i.Review.BookingID,
			&i.Review.ReviewerID,
			&i.Review.RevieweeID,
			&i.Review.Rating,
			&i.Review.Comment,
			&i.Review.CreatedAt,
			&i.User.ID,
			&i.User.Email,
			&i.User.PasswordHash,
			&i.User.FullName,
			&i.User.Phone,
			&i.User.Role,
			&i.User.AvatarUrl,
			&i.User.IsVerified,
			&i.User.BackgroundCheckPassed,
			&i.User.CreatedAt,
			&i.User.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReviewsByReviewee = `-- name: ListReviewsByReviewee :many
SELECT reviews.id, reviews.booking_id, reviews.reviewer_id, reviews.reviewee_id, reviews.rating, reviews.comment, reviews.created_at, users.id, users.email, users.password_hash, users.full_name, users.phone, users.role, users.avatar_url, users.is_verified, users.background_check_passed, users.created_at, users.updated_at
FROM reviews
JOIN users ON users.id = reviews.reviewer_id
WHERE reviews.reviewee_id = $1
ORDER BY reviews.created_at DESC
`

type ListReviewsByRevieweeRow struct {
	Review Review `json:"review"`
	User   User   `json:"user"`
}

func (q *Queries) ListReviewsByReviewee(ctx context.Context, revieweeID int64) ([]ListReviewsByRevieweeRow, error) {
	rows, err := q.db.Query(ctx, listReviewsByReviewee, revieweeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListReviewsByRevieweeRow{}
	for rows.Next() {
		var i ListReviewsByRevieweeRow
		if err := rows.Scan(
			&i.Review.ID,
			&i.Review.BookingID,
			&i.Review.ReviewerID,
			&i.Review.RevieweeID,
			&i.Review.Rating,
			&i.Review.Comment,
			&i.Review.CreatedAt,
			&i.User.ID,
			&i.User.Email,
			&i.User.PasswordHash,
			&i.User.FullName,
			&i.User.Phone,
			&i.User.Role,
			&i.User.AvatarUrl,
			&i.User.IsVerified,
			&i.User.BackgroundCheckPassed,
			&i.User.CreatedAt,
			&i.User.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
