// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tasker_availability.sql

package db

import (
	"context"
)

const createTaskerAvailability = `-- name: CreateTaskerAvailability :one
INSERT INTO tasker_availability (tasker_id, day_of_week, start_time, end_time)
VALUES ($1, $2, $3, $4)
RETURNING id, tasker_id, day_of_week, start_time, end_time
`

type CreateTaskerAvailabilityParams struct {
	TaskerID  int64  `json:"tasker_id"`
	DayOfWeek int32  `json:"day_of_week"`
	StartTime string `json:"start_time"`
	EndTime   string `json:"end_time"`
}

func (q *Queries) CreateTaskerAvailability(ctx context.Context, arg CreateTaskerAvailabilityParams) (TaskerAvailability, error) {
	row := q.db.QueryRow(ctx, createTaskerAvailability,
		arg.TaskerID,
		arg.DayOfWeek,
		arg.StartTime,
		arg.EndTime,
	)
	var i TaskerAvailability
	err := row.Scan(
		&i.ID,
		&i.TaskerID,
		&i.DayOfWeek,
		&i.StartTime,
		&i.EndTime,
	)
	return i, err
}

const deleteTaskerAvailability = `-- name: DeleteTaskerAvailability :exec
DELETE FROM tasker_availability
WHERE tasker_id = $1
`

func (q *Queries) DeleteTaskerAvailability(ctx context.Context, taskerID int64) error {
	_, err := q.db.Exec(ctx, deleteTaskerAvailability, taskerID)
	return err
}

const listTaskerAvailability = `-- name: ListTaskerAvailability :many
SELECT id, tasker_id, day_of_week, start_time, end_time FROM tasker_availability
WHERE tasker_id = $1
ORDER BY day_of_week ASC, start_time ASC
`

func (q *Queries) ListTaskerAvailability(ctx context.Context, taskerID int64) ([]TaskerAvailability, error) {
	rows, err := q.db.Query(ctx, listTaskerAvailability, taskerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskerAvailability{}
	for rows.Next() {
		var i TaskerAvailability
		if err := rows.Scan(
			&i.ID,
			&i.TaskerID,
			&i.DayOfWeek,
			&i.StartTime,
			&i.EndTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskerAvailabilityByTaskerIDs = `-- name: ListTaskerAvailabilityByTaskerIDs :many
SELECT id, tasker_id, day_of_week, start_time, end_time FROM tasker_availability
WHERE tasker_id = ANY($1::bigint[])
ORDER BY tasker_id, day_of_week ASC, start_time ASC
`

func (q *Queries) ListTaskerAvailabilityByTaskerIDs(ctx context.Context, taskerIds []int64) ([]TaskerAvailability, error) {
	rows, err := q.db.Query(ctx, listTaskerAvailabilityByTaskerIDs, taskerIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TaskerAvailability{}
	for rows.Next() {
		var i TaskerAvailability
		if err := rows.Scan(
			&i.ID,
			&i.TaskerID,
			&i.DayOfWeek,
			&i.StartTime,
			&i.EndTime,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
