// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tasker_profiles.sql

package db

import (
	"context"
)

const createTaskerProfile = `-- name: CreateTaskerProfile :one
INSERT INTO tasker_profiles (
  user_id,
  bio,
  hourly_rate,
  years_experience,
  service_radius_km,
  is_available
) VALUES (
  $1, $2, $3, $4, $5, $6
) RETURNING id, user_id, bio, hourly_rate, years_experience, service_radius_km, is_available, avg_rating, total_reviews, created_at, updated_at
`

type CreateTaskerProfileParams struct {
	UserID          int64   `json:"user_id"`
	Bio             string  `json:"bio"`
	HourlyRate      float64 `json:"hourly_rate"`
	YearsExperience int32   `json:"years_experience"`
	ServiceRadiusKm float64 `json:"service_radius_km"`
	IsAvailable     bool    `json:"is_available"`
}

func (q *Queries) CreateTaskerProfile(ctx context.Context, arg CreateTaskerProfileParams) (TaskerProfile, error) {
	row := q.db.QueryRow(ctx, createTaskerProfile,
		arg.UserID,
		arg.Bio,
		arg.HourlyRate,
		arg.YearsExperience,
		arg.ServiceRadiusKm,
		arg.IsAvailable,
	)
	var i TaskerProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Bio,
		&i.HourlyRate,
		&i.YearsExperience,
		&i.ServiceRadiusKm,
		&i.IsAvailable,
		&i.AvgRating,
		&i.TotalReviews,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTaskerProfile = `-- name: GetTaskerProfile :one
SELECT id, user_id, bio, hourly_rate, years_experience, service_radius_km, is_available, avg_rating, total_reviews, created_at, updated_at FROM tasker_profiles
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetTaskerProfile(ctx context.Context, id int64) (TaskerProfile, error) {
	row := q.db.QueryRow(ctx, getTaskerProfile, id)
	var i TaskerProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Bio,
		&i.HourlyRate,
		&i.YearsExperience,
		&i.ServiceRadiusKm,
		&i.IsAvailable,
		&i.AvgRating,
		&i.TotalReviews,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTaskerProfileByUserID = `-- name: GetTaskerProfileByUserID :one
SELECT id, user_id, bio, hourly_rate, years_experience, service_radius_km, is_available, avg_rating, total_reviews, created_at, updated_at FROM tasker_profiles
WHERE user_id = $1 LIMIT 1
`

func (q *Queries) GetTaskerProfileByUserID(ctx context.Context, userID int64) (TaskerProfile, error) {
	row := q.db.QueryRow(ctx, getTaskerProfileByUserID, userID)
	var i TaskerProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Bio,
		&i.HourlyRate,
		&i.YearsExperience,
		&i.ServiceRadiusKm,
		&i.IsAvailable,
		&i.AvgRating,
		&i.TotalReviews,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTaskerProfileWithUser = `-- name: GetTaskerProfileWithUser :one
SELECT tasker_profiles.id, tasker_profiles.user_id, tasker_profiles.bio, tasker_profiles.hourly_rate, tasker_profiles.years_experience, tasker_profiles.service_radius_km, tasker_profiles.is_available, tasker_profiles.avg_rating, tasker_profiles.total_reviews, tasker_profiles.created_at, tasker_profiles.updated_at, users.id, users.email, users.password_hash, users.full_name, users.phone, users.role, users.avatar_url, users.is_verified, users.background_check_passed, users.created_at, users.updated_at
FROM tasker_profiles
JOIN users ON users.id = tasker_profiles.user_id
WHERE tasker_profiles.id = $1 LIMIT 1
`

type GetTaskerProfileWithUserRow struct {
	TaskerProfile TaskerProfile `json:"tasker_profile"`
	User          User          `json:"user"`
}

func (q *Queries) GetTaskerProfileWithUser(ctx context.Context, id int64) (GetTaskerProfileWithUserRow, error) {
	row := q.db.QueryRow(ctx, getTaskerProfileWithUser, id)
	var i GetTaskerProfileWithUserRow
	err := row.Scan(
		&i.TaskerProfile.ID,
		&i.TaskerProfile.UserID,
		&i.TaskerProfile.Bio,
		&i.TaskerProfile.HourlyRate,
		&i.TaskerProfile.YearsExperience,
		&i.TaskerProfile.ServiceRadiusKm,
		&i.TaskerProfile.IsAvailable,
		&i.TaskerProfile.AvgRating,
		&i.TaskerProfile.TotalReviews,
		&i.TaskerProfile.CreatedAt,
		&i.TaskerProfile.UpdatedAt,
		&i.User.ID,
		&i.User.Email,
		&i.User.PasswordHash,
		&i.User.FullName,
		&i.User.Phone,
		&i.User.Role,
		&i.User.AvatarUrl,
		&i.User.IsVerified,
		&i.User.BackgroundCheckPassed,
		&i.User.CreatedAt,
		&i.User.UpdatedAt,
	)
	return i, err
}

const getTaskerProfileWithUserByUserID = `-- name: GetTaskerProfileWithUserByUserID :one
SELECT tasker_profiles.id, tasker_profiles.user_id, tasker_profiles.bio, tasker_profiles.hourly_rate, tasker_profiles.years_experience, tasker_profiles.service_radius_km, tasker_profiles.is_available, tasker_profiles.avg_rating, tasker_profiles.total_reviews, tasker_profiles.created_at, tasker_profiles.updated_at, users.id, users.email, users.password_hash, users.full_name, users.phone, users.role, users.avatar_url, users.is_verified, users.background_check_passed, users.created_at, users.updated_at
FROM tasker_profiles
JOIN users ON users.id = tasker_profiles.user_id
WHERE tasker_profiles.user_id = $1 LIMIT 1
`

type GetTaskerProfileWithUserByUserIDRow struct {
	TaskerProfile TaskerProfile `json:"tasker_profile"`
	User          User          `json:"user"`
}

func (q *Queries) GetTaskerProfileWithUserByUserID(ctx context.Context, userID int64) (GetTaskerProfileWithUserByUserIDRow, error) {
	row := q.db.QueryRow(ctx, getTaskerProfileWithUserByUserID, userID)
	var i GetTaskerProfileWithUserByUserIDRow
	err := row.Scan(
		&i.TaskerProfile.ID,
		&i.TaskerProfile.UserID,
		&i.TaskerProfile.Bio,
		&i.TaskerProfile.HourlyRate,
		&i.TaskerProfile.YearsExperience,
		&i.TaskerProfile.ServiceRadiusKm,
		&i.TaskerProfile.IsAvailable,
		&i.TaskerProfile.AvgRating,
		&i.TaskerProfile.TotalReviews,
		&i.TaskerProfile.CreatedAt,
		&i.TaskerProfile.UpdatedAt,
		&i.User.ID,
		&i.User.Email,
		&i.User.PasswordHash,
		&i.User.FullName,
		&i.User.Phone,
		&i.User.Role,
		&i.User.AvatarUrl,
		&i.User.IsVerified,
		&i.User.BackgroundCheckPassed,
		&i.User.CreatedAt,
		&i.User.UpdatedAt,
	)
	return i, err
}

const listTaskerProfiles = `-- name: ListTaskerProfiles :many
SELECT tasker_profiles.id, tasker_profiles.user_id, tasker_profiles.bio, tasker_profiles.hourly_rate, tasker_profiles.years_experience, tasker_profiles.service_radius_km, tasker_profiles.is_available, tasker_profiles.avg_rating, tasker_profiles.total_reviews, tasker_profiles.created_at, tasker_profiles.updated_at, users.id, users.email, users.password_hash, users.full_name, users.phone, users.role, users.avatar_url, users.is_verified, users.background_check_passed, users.created_at, users.updated_at
FROM tasker_profiles
JOIN users ON users.id = tasker_profiles.user_id
WHERE
  ($1::boolean IS NOT TRUE OR tasker_profiles.is_available = TRUE)
  AND (
    $2::bigint IS NULL
    OR EXISTS (
      SELECT 1 FROM tasker_skills
      WHERE tasker_skills.tasker_id = tasker_profiles.id
        AND tasker_skills.category_id = $2
    )
  )
  AND ($3::numeric IS NULL OR tasker_profiles.hourly_rate <= $3)
  AND ($4::numeric IS NULL OR tasker_profiles.avg_rating >= $4)
  AND (
    $5::text IS NULL
    OR users.full_name ILIKE '%' || $5 || '%'
    OR tasker_profiles.bio ILIKE '%' || $5 || '%'
  )
ORDER BY tasker_profiles.avg_rating DESC, tasker_profiles.total_reviews DESC
`

type ListTaskerProfilesParams struct {
	AvailableOnly *bool    `json:"available_only"`
	CategoryID    *int64   `json:"category_id"`
	MaxRate       *float64 `json:"max_rate"`
	MinRating     *float64 `json:"min_rating"`
	Search        *string  `json:"search"`
}

type ListTaskerProfilesRow struct {
	TaskerProfile TaskerProfile `json:"tasker_profile"`
	User          User          `json:"user"`
}

// The directory listing. Every filter is optional: a NULL argument drops its
// own clause, which is how one prepared statement covers what the handler used
// to assemble by chaining query builders.
//
// The category filter is an EXISTS rather than a JOIN so a tasker holding
// several skills still comes back as one row.
func (q *Queries) ListTaskerProfiles(ctx context.Context, arg ListTaskerProfilesParams) ([]ListTaskerProfilesRow, error) {
	rows, err := q.db.Query(ctx, listTaskerProfiles,
		arg.AvailableOnly,
		arg.CategoryID,
		arg.MaxRate,
		arg.MinRating,
		arg.Search,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTaskerProfilesRow{}
	for rows.Next() {
		var i ListTaskerProfilesRow
		if err := rows.Scan(
			&i.TaskerProfile.ID,
			&i.TaskerProfile.UserID,
			&i.TaskerProfile.Bio,
			&i.TaskerProfile.HourlyRate,
			&i.TaskerProfile.YearsExperience,
			&i.TaskerProfile.ServiceRadiusKm,
			&i.TaskerProfile.IsAvailable,
			&i.TaskerProfile.AvgRating,
			&i.TaskerProfile.TotalReviews,
			&i.TaskerProfile.CreatedAt,
			&i.TaskerProfile.UpdatedAt,
			&i.User.ID,
			&i.User.Email,
			&i.User.PasswordHash,
			&i.User.FullName,
			&i.User.Phone,
			&i.User.Role,
			&i.User.AvatarUrl,
			&i.User.IsVerified,
			&i.User.BackgroundCheckPassed,
			&i.User.CreatedAt,
			&i.User.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTaskerProfile = `-- name: UpdateTaskerProfile :one
UPDATE tasker_profiles
SET
  bio = COALESCE($1, bio),
  hourly_rate = COALESCE($2, hourly_rate),
  years_experience = COALESCE($3, years_experience),
  service_radius_km = COALESCE($4, service_radius_km),
  is_available = COALESCE($5, is_available),
  updated_at = now()
WHERE id = $6
RETURNING id, user_id, bio, hourly_rate, years_experience, service_radius_km, is_available, avg_rating, total_reviews, created_at, updated_at
`

type UpdateTaskerProfileParams struct {
	Bio             *string  `json:"bio"`
	HourlyRate      *float64 `json:"hourly_rate"`
	YearsExperience *int32   `json:"years_experience"`
	ServiceRadiusKm *float64 `json:"service_radius_km"`
	IsAvailable     *bool    `json:"is_available"`
	ID              int64    `json:"id"`
}

// Partial update: the dashboard sends only the fields the tasker touched, and
// a NULL here means "not supplied" rather than "set to zero".
func (q *Queries) UpdateTaskerProfile(ctx context.Context, arg UpdateTaskerProfileParams) (TaskerProfile, error) {
	row := q.db.QueryRow(ctx, updateTaskerProfile,
		arg.Bio,
		arg.HourlyRate,
		arg.YearsExperience,
		arg.ServiceRadiusKm,
		arg.IsAvailable,
		arg.ID,
	)
	var i TaskerProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Bio,
		&i.HourlyRate,
		&i.YearsExperience,
		&i.ServiceRadiusKm,
		&i.IsAvailable,
		&i.AvgRating,
		&i.TotalReviews,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTaskerRatingByUserID = `-- name: UpdateTaskerRatingByUserID :exec
UPDATE tasker_profiles
SET avg_rating = $2, total_reviews = $3, updated_at = now()
WHERE user_id = $1
`

type UpdateTaskerRatingByUserIDParams struct {
	UserID       int64   `json:"user_id"`
	AvgRating    float64 `json:"avg_rating"`
	TotalReviews int32   `json:"total_reviews"`
}

// Refreshes the denormalised rating columns after a review lands. A no-op when
// the reviewee is a client, who has no tasker profile -- hence :exec rather
// than :one, which would report ErrNoRows for a perfectly normal case.
func (q *Queries) UpdateTaskerRatingByUserID(ctx context.Context, arg UpdateTaskerRatingByUserIDParams) error {
	_, err := q.db.Exec(ctx, updateTaskerRatingByUserID, arg.UserID, arg.AvgRating, arg.TotalReviews)
	return err
}
