// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: task_applications.sql

package db

import (
	"context"
)

const countApplicationsByTaskAndTasker = `-- name: CountApplicationsByTaskAndTasker :one
SELECT COUNT(*) FROM task_applications
WHERE task_id = $1 AND tasker_id = $2
`

type CountApplicationsByTaskAndTaskerParams struct {
	TaskID   int64 `json:"task_id"`
	TaskerID int64 `json:"tasker_id"`
}

func (q *Queries) CountApplicationsByTaskAndTasker(ctx context.Context, arg CountApplicationsByTaskAndTaskerParams) (int64, error) {
	row := q.db.QueryRow(ctx, countApplicationsByTaskAndTasker, arg.TaskID, arg.TaskerID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTaskApplication = `-- name: CreateTaskApplication :one
INSERT INTO task_applications (task_id, tasker_id, proposed_rate, cover_note, status)
VALUES ($1, $2, $3, $4, 'pending')
RETURNING id, task_id, tasker_id, proposed_rate, cover_note, status, created_at
`

type CreateTaskApplicationParams struct {
	TaskID       int64   `json:"task_id"`
	TaskerID     int64   `json:"tasker_id"`
	ProposedRate float64 `json:"proposed_rate"`
	CoverNote    string  `json:"cover_note"`
}

func (q *Queries) CreateTaskApplication(ctx context.Context, arg CreateTaskApplicationParams) (TaskApplication, error) {
	row := q.db.QueryRow(ctx, createTaskApplication,
		arg.TaskID,
		arg.TaskerID,
		arg.ProposedRate,
		arg.CoverNote,
	)
	var i TaskApplication
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.TaskerID,
		&i.ProposedRate,
		&i.CoverNote,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getApplicationWithTasker = `-- name: GetApplicationWithTasker :one
SELECT task_applications.id, task_applications.task_id, task_applications.tasker_id, task_applications.proposed_rate, task_applications.cover_note, task_applications.status, task_applications.created_at, tasker_profiles.id, tasker_profiles.user_id, tasker_profiles.bio, tasker_profiles.hourly_rate, tasker_profiles.years_experience, tasker_profiles.service_radius_km, tasker_profiles.is_available, tasker_profiles.avg_rating, tasker_profiles.total_reviews, tasker_profiles.created_at, tasker_profiles.updated_at, users.id, users.email, users.password_hash, users.full_name, users.phone, users.role, users.avatar_url, users.is_verified, users.background_check_passed, users.created_at, users.updated_at
FROM task_applications
JOIN tasker_profiles ON tasker_profiles.id = task_applications.tasker_id
JOIN users ON users.id = tasker_profiles.user_id
WHERE task_applications.id = $1 LIMIT 1
`

type GetApplicationWithTaskerRow struct {
	TaskApplication TaskApplication `json:"task_application"`
	TaskerProfile   TaskerProfile   `json:"tasker_profile"`
	User            User            `json:"user"`
}

func (q *Queries) GetApplicationWithTasker(ctx context.Context, id int64) (GetApplicationWithTaskerRow, error) {
	row := q.db.QueryRow(ctx, getApplicationWithTasker, id)
	var i GetApplicationWithTaskerRow
	err := row.Scan(
		&i.TaskApplication.ID,
		&i.TaskApplication.TaskID,
		&i.TaskApplication.TaskerID,
		&i.TaskApplication.ProposedRate,
		&i.TaskApplication.CoverNote,
		&i.TaskApplication.Status,
		&i.TaskApplication.CreatedAt,
		&i.TaskerProfile.ID,
		&i.TaskerProfile.UserID,
		&i.TaskerProfile.Bio,
		&i.TaskerProfile.HourlyRate,
		&i.TaskerProfile.YearsExperience,
		&i.TaskerProfile.ServiceRadiusKm,
		&i.TaskerProfile.IsAvailable,
		&i.TaskerProfile.AvgRating,
		&i.TaskerProfile.TotalReviews,
		&i.TaskerProfile.CreatedAt,
		&i.TaskerProfile.UpdatedAt,
		&i.User.ID,
		&i.User.Email,
		&i.User.PasswordHash,
		&i.User.FullName,
		&i.User.Phone,
		&i.User.Role,
		&i.User.AvatarUrl,
		&i.User.IsVerified,
		&i.User.BackgroundCheckPassed,
		&i.User.CreatedAt,
		&i.User.UpdatedAt,
	)
	return i, err
}

const getTaskApplication = `-- name: GetTaskApplication :one
SELECT id, task_id, tasker_id, proposed_rate, cover_note, status, created_at FROM task_applications
WHERE id = $1 AND task_id = $2 LIMIT 1
`

type GetTaskApplicationParams struct {
	ID     int64 `json:"id"`
	TaskID int64 `json:"task_id"`
}

func (q *Queries) GetTaskApplication(ctx context.Context, arg GetTaskApplicationParams) (TaskApplication, error) {
	row := q.db.QueryRow(ctx, getTaskApplication, arg.ID, arg.TaskID)
	var i TaskApplication
	err := row.Scan(
		&i.ID,
		&i.TaskID,
		&i.TaskerID,
		&i.ProposedRate,
		&i.CoverNote,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const listApplicationsByTaskIDs = `-- name: ListApplicationsByTaskIDs :many
SELECT task_applications.id, task_applications.task_id, task_applications.tasker_id, task_applications.proposed_rate, task_applications.cover_note, task_applications.status, task_applications.created_at, tasker_profiles.id, tasker_profiles.user_id, tasker_profiles.bio, tasker_profiles.hourly_rate, tasker_profiles.years_experience, tasker_profiles.service_radius_km, tasker_profiles.is_available, tasker_profiles.avg_rating, tasker_profiles.total_reviews, tasker_profiles.created_at, tasker_profiles.updated_at, users.id, users.email, users.password_hash, users.full_name, users.phone, users.role, users.avatar_url, users.is_verified, users.background_check_passed, users.created_at, users.updated_at
FROM task_applications
JOIN tasker_profiles ON tasker_profiles.id = task_applications.tasker_id
JOIN users ON users.id = tasker_profiles.user_id
WHERE task_applications.task_id = ANY($1::bigint[])
ORDER BY task_applications.created_at DESC
`

type ListApplicationsByTaskIDsRow struct {
	TaskApplication TaskApplication `json:"task_application"`
	TaskerProfile   TaskerProfile   `json:"tasker_profile"`
	User            User            `json:"user"`
}

// Batch form so a page of tasks costs one query for all their applications
// rather than one per task.
func (q *Queries) ListApplicationsByTaskIDs(ctx context.Context, taskIds []int64) ([]ListApplicationsByTaskIDsRow, error) {
	rows, err := q.db.Query(ctx, listApplicationsByTaskIDs, taskIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListApplicationsByTaskIDsRow{}
	for rows.Next() {
		var i ListApplicationsByTaskIDsRow
		if err := rows.Scan(
			&i.TaskApplication.ID,
			&i.TaskApplication.TaskID,
			&i.TaskApplication.TaskerID,
			&i.TaskApplication.ProposedRate,
			&i.TaskApplication.CoverNote,
			&i.TaskApplication.Status,
			&i.TaskApplication.CreatedAt,
			&i.TaskerProfile.ID,
			&i.TaskerProfile.UserID,
			&i.TaskerProfile.Bio,
			&i.TaskerProfile.HourlyRate,
			&i.TaskerProfile.YearsExperience,
			&i.TaskerProfile.ServiceRadiusKm,
			&i.TaskerProfile.IsAvailable,
			&i.TaskerProfile.AvgRating,
			&i.TaskerProfile.TotalReviews,
			&i.TaskerProfile.CreatedAt,
			&i.TaskerProfile.UpdatedAt,
			&i.User.ID,
			&i.User.Email,
			&i.User.PasswordHash,
			&i.User.FullName,
			&i.User.Phone,
			&i.User.Role,
			&i.User.AvatarUrl,
			&i.User.IsVerified,
			&i.User.BackgroundCheckPassed,
			&i.User.CreatedAt,
			&i.User.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listApplicationsByTasker = `-- name: ListApplicationsByTasker :many
SELECT task_applications.id, task_applications.task_id, task_applications.tasker_id, task_applications.proposed_rate, task_applications.cover_note, task_applications.status, task_applications.created_at, tasks.id, tasks.client_id, tasks.category_id, tasks.title, tasks.description, tasks.location_address, tasks.location_lat, tasks.location_lng, tasks.budget_type, tasks.budget_amount, tasks.status, tasks.scheduled_at, tasks.created_at, tasks.updated_at, categories.id, categories.name, categories.icon_url, categories.description, users.id, users.email, users.password_hash, users.full_name, users.phone, users.role, users.avatar_url, users.is_verified, users.background_check_passed, users.created_at, users.updated_at
FROM task_applications
JOIN tasks ON tasks.id = task_applications.task_id
JOIN categories ON categories.id = tasks.category_id
JOIN users ON users.id = tasks.client_id
WHERE task_applications.tasker_id = $1
ORDER BY task_applications.created_at DESC
`

type ListApplicationsByTaskerRow struct {
	TaskApplication TaskApplication `json:"task_application"`
	Task            Task            `json:"task"`
	Category        Category        `json:"category"`
	User            User            `json:"user"`
}

func (q *Queries) ListApplicationsByTasker(ctx context.Context, taskerID int64) ([]ListApplicationsByTaskerRow, error) {
	rows, err := q.db.Query(ctx, listApplicationsByTasker, taskerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListApplicationsByTaskerRow{}
	for rows.Next() {
		var i ListApplicationsByTaskerRow
		if err := rows.Scan(
			&i.TaskApplication.ID,
			&i.TaskApplication.TaskID,
			&i.TaskApplication.TaskerID,
			&i.TaskApplication.ProposedRate,
			&i.TaskApplication.CoverNote,
			&i.TaskApplication.Status,
			&i.TaskApplication.CreatedAt,
			&i.Task.ID,
			&i.Task.ClientID,
			&i.Task.CategoryID,
			&i.Task.Title,
			&i.Task.Description,
			&i.Task.LocationAddress,
			&i.Task.LocationLat,
			&i.Task.LocationLng,
			&i.Task.BudgetType,
			&i.Task.BudgetAmount,
			&i.Task.Status,
			&i.Task.ScheduledAt,
			&i.Task.CreatedAt,
			&i.Task.UpdatedAt,
			&i.Category.ID,
			&i.Category.Name,
			&i.Category.IconUrl,
			&i.Category.Description,
			&i.User.ID,
			&i.User.Email,
			&i.User.PasswordHash,
			&i.User.FullName,
			&i.User.Phone,
			&i.User.Role,
			&i.User.AvatarUrl,
			&i.User.IsVerified,
			&i.User.BackgroundCheckPassed,
			&i.User.CreatedAt,
			&i.User.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rejectRivalApplications = `-- name: RejectRivalApplications :exec
UPDATE task_applications
SET status = 'rejected'
WHERE task_id = $1 AND id <> $2
`

type RejectRivalApplicationsParams struct {
	TaskID int64 `json:"task_id"`
	ID     int64 `json:"id"`
}

// Accepting one application closes the rest for that task in the same
// transaction, so a client can never book two taskers for one job.
func (q *Queries) RejectRivalApplications(ctx context.Context, arg RejectRivalApplicationsParams) error {
	_, err := q.db.Exec(ctx, rejectRivalApplications, arg.TaskID, arg.ID)
	return err
}

const updateApplicationStatus = `-- name: UpdateApplicationStatus :exec
UPDATE task_applications
SET status = $2
WHERE id = $1
`

type UpdateApplicationStatusParams struct {
	ID     int64  `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdateApplicationStatus(ctx context.Context, arg UpdateApplicationStatusParams) error {
	_, err := q.db.Exec(ctx, updateApplicationStatus, arg.ID, arg.Status)
	return err
}
