// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tasks.sql

package db

import (
	"context"
	"time"
)

const createTask = `-- name: CreateTask :one
INSERT INTO tasks (
  client_id,
  category_id,
  title,
  description,
  location_address,
  location_lat,
  location_lng,
  budget_type,
  budget_amount,
  scheduled_at,
  status
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, 'open'
) RETURNING id, client_id, category_id, title, description, location_address, location_lat, location_lng, budget_type, budget_amount, status, scheduled_at, created_at, updated_at
`

type CreateTaskParams struct {
	ClientID        int64      `json:"client_id"`
	CategoryID      int64      `json:"category_id"`
	Title           string     `json:"title"`
	Description     string     `json:"description"`
	LocationAddress string     `json:"location_address"`
	LocationLat     float64    `json:"location_lat"`
	LocationLng     float64    `json:"location_lng"`
	BudgetType      string     `json:"budget_type"`
	BudgetAmount    float64    `json:"budget_amount"`
	ScheduledAt     *time.Time `json:"scheduled_at"`
}

func (q *Queries) CreateTask(ctx context.Context, arg CreateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, createTask,
		arg.ClientID,
		arg.CategoryID,
		arg.Title,
		arg.Description,
		arg.LocationAddress,
		arg.LocationLat,
		arg.LocationLng,
		arg.BudgetType,
		arg.BudgetAmount,
		arg.ScheduledAt,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.CategoryID,
		&i.Title,
		&i.Description,
		&i.LocationAddress,
		&i.LocationLat,
		&i.LocationLng,
		&i.BudgetType,
		&i.BudgetAmount,
		&i.Status,
		&i.ScheduledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTask = `-- name: GetTask :one
SELECT id, client_id, category_id, title, description, location_address, location_lat, location_lng, budget_type, budget_amount, status, scheduled_at, created_at, updated_at FROM tasks
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetTask(ctx context.Context, id int64) (Task, error) {
	row := q.db.QueryRow(ctx, getTask, id)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.CategoryID,
		&i.Title,
		&i.Description,
		&i.LocationAddress,
		&i.LocationLat,
		&i.LocationLng,
		&i.BudgetType,
		&i.BudgetAmount,
		&i.Status,
		&i.ScheduledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTaskWithRelations = `-- name: GetTaskWithRelations :one
SELECT tasks.id, tasks.client_id, tasks.category_id, tasks.title, tasks.description, tasks.location_address, tasks.location_lat, tasks.location_lng, tasks.budget_type, tasks.budget_amount, tasks.status, tasks.scheduled_at, tasks.created_at, tasks.updated_at, categories.id, categories.name, categories.icon_url, categories.description, users.id, users.email, users.password_hash, users.full_name, users.phone, users.role, users.avatar_url, users.is_verified, users.background_check_passed, users.created_at, users.updated_at
FROM tasks
JOIN categories ON categories.id = tasks.category_id
JOIN users ON users.id = tasks.client_id
WHERE tasks.id = $1 LIMIT 1
`

type GetTaskWithRelationsRow struct {
	Task     Task     `json:"task"`
	Category Category `json:"category"`
	User     User     `json:"user"`
}

func (q *Queries) GetTaskWithRelations(ctx context.Context, id int64) (GetTaskWithRelationsRow, error) {
	row := q.db.QueryRow(ctx, getTaskWithRelations, id)
	var i GetTaskWithRelationsRow
	err := row.Scan(
		&i.Task.ID,
		&i.Task.ClientID,
		&i.Task.CategoryID,
		&i.Task.Title,
		&i.Task.Description,
		&i.Task.LocationAddress,
		&i.Task.LocationLat,
		&i.Task.LocationLng,
		&i.Task.BudgetType,
		&i.Task.BudgetAmount,
		&i.Task.Status,
		&i.Task.ScheduledAt,
		&i.Task.CreatedAt,
		&i.Task.UpdatedAt,
		&i.Category.ID,
		&i.Category.Name,
		&i.Category.IconUrl,
		&i.Category.Description,
		&i.User.ID,
		&i.User.Email,
		&i.User.PasswordHash,
		&i.User.FullName,
		&i.User.Phone,
		&i.User.Role,
		&i.User.AvatarUrl,
		&i.User.IsVerified,
		&i.User.BackgroundCheckPassed,
		&i.User.CreatedAt,
		&i.User.UpdatedAt,
	)
	return i, err
}

const listOpenTasks = `-- name: ListOpenTasks :many
SELECT tasks.id, tasks.client_id, tasks.category_id, tasks.title, tasks.description, tasks.location_address, tasks.location_lat, tasks.location_lng, tasks.budget_type, tasks.budget_amount, tasks.status, tasks.scheduled_at, tasks.created_at, tasks.updated_at, categories.id, categories.name, categories.icon_url, categories.description, users.id, users.email, users.password_hash, users.full_name, users.phone, users.role, users.avatar_url, users.is_verified, users.background_check_passed, users.created_at, users.updated_at
FROM tasks
JOIN categories ON categories.id = tasks.category_id
JOIN users ON users.id = tasks.client_id
WHERE tasks.status = 'open'
  AND ($1::bigint IS NULL OR tasks.category_id = $1)
  AND ($2::numeric IS NULL OR tasks.budget_amount >= $2)
  AND (
    $3::text IS NULL
    OR tasks.title ILIKE '%' || $3 || '%'
    OR tasks.description ILIKE '%' || $3 || '%'
  )
ORDER BY tasks.created_at DESC
`

type ListOpenTasksParams struct {
	CategoryID *int64   `json:"category_id"`
	MinBudget  *float64 `json:"min_budget"`
	Search     *string  `json:"search"`
}

type ListOpenTasksRow struct {
	Task     Task     `json:"task"`
	Category Category `json:"category"`
	User     User     `json:"user"`
}

// The marketplace feed taskers browse. As with ListTaskerProfiles, each filter
// is skipped when its argument is NULL.
func (q *Queries) ListOpenTasks(ctx context.Context, arg ListOpenTasksParams) ([]ListOpenTasksRow, error) {
	rows, err := q.db.Query(ctx, listOpenTasks, arg.CategoryID, arg.MinBudget, arg.Search)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOpenTasksRow{}
	for rows.Next() {
		var i ListOpenTasksRow
		if err := rows.Scan(
			&i.Task.ID,
			&i.Task.ClientID,
			&i.Task.CategoryID,
			&i.Task.Title,
			&i.Task.Description,
			&i.Task.LocationAddress,
			&i.Task.LocationLat,
			&i.Task.LocationLng,
			&i.Task.BudgetType,
			&i.Task.BudgetAmount,
			&i.Task.Status,
			&i.Task.ScheduledAt,
			&i.Task.CreatedAt,
			&i.Task.UpdatedAt,
			&i.Category.ID,
			&i.Category.Name,
			&i.Category.IconUrl,
			&i.Category.Description,
			&i.User.ID,
			&i.User.Email,
			&i.User.PasswordHash,
			&i.User.FullName,
			&i.User.Phone,
			&i.User.Role,
			&i.User.AvatarUrl,
			&i.User.IsVerified,
			&i.User.BackgroundCheckPassed,
			&i.User.CreatedAt,
			&i.User.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTasksByClient = `-- name: ListTasksByClient :many
SELECT tasks.id, tasks.client_id, tasks.category_id, tasks.title, tasks.description, tasks.location_address, tasks.location_lat, tasks.location_lng, tasks.budget_type, tasks.budget_amount, tasks.status, tasks.scheduled_at, tasks.created_at, tasks.updated_at, categories.id, categories.name, categories.icon_url, categories.description, users.id, users.email, users.password_hash, users.full_name, users.phone, users.role, users.avatar_url, users.is_verified, users.background_check_passed, users.created_at, users.updated_at
FROM tasks
JOIN categories ON categories.id = tasks.category_id
JOIN users ON users.id = tasks.client_id
WHERE tasks.client_id = $1
ORDER BY tasks.created_at DESC
`

type ListTasksByClientRow struct {
	Task     Task     `json:"task"`
	Category Category `json:"category"`
	User     User     `json:"user"`
}

func (q *Queries) ListTasksByClient(ctx context.Context, clientID int64) ([]ListTasksByClientRow, error) {
	rows, err := q.db.Query(ctx, listTasksByClient, clientID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTasksByClientRow{}
	for rows.Next() {
		var i ListTasksByClientRow
		if err := rows.Scan(
			&i.Task.ID,
			&i.Task.ClientID,
			&i.Task.CategoryID,
			&i.Task.Title,
			&i.Task.Description,
			&i.Task.LocationAddress,
			&i.Task.LocationLat,
			&i.Task.LocationLng,
			&i.Task.BudgetType,
			&i.Task.BudgetAmount,
			&i.Task.Status,
			&i.Task.ScheduledAt,
			&i.Task.CreatedAt,
			&i.Task.UpdatedAt,
			&i.Category.ID,
			&i.Category.Name,
			&i.Category.IconUrl,
			&i.Category.Description,
			&i.User.ID,
			&i.User.Email,
			&i.User.PasswordHash,
			&i.User.FullName,
			&i.User.Phone,
			&i.User.Role,
			&i.User.AvatarUrl,
			&i.User.IsVerified,
			&i.User.BackgroundCheckPassed,
			&i.User.CreatedAt,
			&i.User.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTask = `-- name: UpdateTask :one
UPDATE tasks
SET
  category_id = $2,
  title = $3,
  description = $4,
  location_address = $5,
  location_lat = $6,
  location_lng = $7,
  budget_type = $8,
  budget_amount = $9,
  scheduled_at = $10,
  updated_at = now()
WHERE id = $1
RETURNING id, client_id, category_id, title, description, location_address, location_lat, location_lng, budget_type, budget_amount, status, scheduled_at, created_at, updated_at
`

type UpdateTaskParams struct {
	ID              int64      `json:"id"`
	CategoryID      int64      `json:"category_id"`
	Title           string     `json:"title"`
	Description     string     `json:"description"`
	LocationAddress string     `json:"location_address"`
	LocationLat     float64    `json:"location_lat"`
	LocationLng     float64    `json:"location_lng"`
	BudgetType      string     `json:"budget_type"`
	BudgetAmount    float64    `json:"budget_amount"`
	ScheduledAt     *time.Time `json:"scheduled_at"`
}

func (q *Queries) UpdateTask(ctx context.Context, arg UpdateTaskParams) (Task, error) {
	row := q.db.QueryRow(ctx, updateTask,
		arg.ID,
		arg.CategoryID,
		arg.Title,
		arg.Description,
		arg.LocationAddress,
		arg.LocationLat,
		arg.LocationLng,
		arg.BudgetType,
		arg.BudgetAmount,
		arg.ScheduledAt,
	)
	var i Task
	err := row.Scan(
		&i.ID,
		&i.ClientID,
		&i.CategoryID,
		&i.Title,
		&i.Description,
		&i.LocationAddress,
		&i.LocationLat,
		&i.LocationLng,
		&i.BudgetType,
		&i.BudgetAmount,
		&i.Status,
		&i.ScheduledAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateTaskStatus = `-- name: UpdateTaskStatus :exec
UPDATE tasks
SET status = $2, updated_at = now()
WHERE id = $1
`

type UpdateTaskStatusParams struct {
	ID     int64  `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdateTaskStatus(ctx context.Context, arg UpdateTaskStatusParams) error {
	_, err := q.db.Exec(ctx, updateTaskStatus, arg.ID, arg.Status)
	return err
}
