// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tasker_skills.sql

package db

import (
	"context"
)

const createTaskerSkill = `-- name: CreateTaskerSkill :one
INSERT INTO tasker_skills (tasker_id, category_id)
VALUES ($1, $2)
ON CONFLICT (tasker_id, category_id) DO NOTHING
RETURNING id, tasker_id, category_id
`

type CreateTaskerSkillParams struct {
	TaskerID   int64 `json:"tasker_id"`
	CategoryID int64 `json:"category_id"`
}

func (q *Queries) CreateTaskerSkill(ctx context.Context, arg CreateTaskerSkillParams) (TaskerSkill, error) {
	row := q.db.QueryRow(ctx, createTaskerSkill, arg.TaskerID, arg.CategoryID)
	var i TaskerSkill
	err := row.Scan(&i.ID, &i.TaskerID, &i.CategoryID)
	return i, err
}

const deleteTaskerSkills = `-- name: DeleteTaskerSkills :exec
DELETE FROM tasker_skills
WHERE tasker_id = $1
`

func (q *Queries) DeleteTaskerSkills(ctx context.Context, taskerID int64) error {
	_, err := q.db.Exec(ctx, deleteTaskerSkills, taskerID)
	return err
}

const listTaskerSkills = `-- name: ListTaskerSkills :many
SELECT tasker_skills.id, tasker_skills.tasker_id, tasker_skills.category_id, categories.id, categories.name, categories.icon_url, categories.description
FROM tasker_skills
JOIN categories ON categories.id = tasker_skills.category_id
WHERE tasker_skills.tasker_id = $1
ORDER BY categories.name ASC
`

type ListTaskerSkillsRow struct {
	TaskerSkill TaskerSkill `json:"tasker_skill"`
	Category    Category    `json:"category"`
}

func (q *Queries) ListTaskerSkills(ctx context.Context, taskerID int64) ([]ListTaskerSkillsRow, error) {
	rows, err := q.db.Query(ctx, listTaskerSkills, taskerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTaskerSkillsRow{}
	for rows.Next() {
		var i ListTaskerSkillsRow
		if err := rows.Scan(
			&i.TaskerSkill.ID,
			&i.TaskerSkill.TaskerID,
			&i.TaskerSkill.CategoryID,
			&i.Category.ID,
			&i.Category.Name,
			&i.Category.IconUrl,
			&i.Category.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTaskerSkillsByTaskerIDs = `-- name: ListTaskerSkillsByTaskerIDs :many
SELECT tasker_skills.id, tasker_skills.tasker_id, tasker_skills.category_id, categories.id, categories.name, categories.icon_url, categories.description
FROM tasker_skills
JOIN categories ON categories.id = tasker_skills.category_id
WHERE tasker_skills.tasker_id = ANY($1::bigint[])
ORDER BY tasker_skills.tasker_id, categories.name ASC
`

type ListTaskerSkillsByTaskerIDsRow struct {
	TaskerSkill TaskerSkill `json:"tasker_skill"`
	Category    Category    `json:"category"`
}

// Batch form for list endpoints: one query for the whole page of taskers
// instead of one per row, which is what Preload was doing.
func (q *Queries) ListTaskerSkillsByTaskerIDs(ctx context.Context, taskerIds []int64) ([]ListTaskerSkillsByTaskerIDsRow, error) {
	rows, err := q.db.Query(ctx, listTaskerSkillsByTaskerIDs, taskerIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTaskerSkillsByTaskerIDsRow{}
	for rows.Next() {
		var i ListTaskerSkillsByTaskerIDsRow
		if err := rows.Scan(
			&i.TaskerSkill.ID,
			&i.TaskerSkill.TaskerID,
			&i.TaskerSkill.CategoryID,
			&i.Category.ID,
			&i.Category.Name,
			&i.Category.IconUrl,
			&i.Category.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
