// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  email,
  password_hash,
  full_name,
  phone,
  role,
  is_verified,
  background_check_passed
) VALUES (
  $1, $2, $3, $4, $5, $6, $7
) RETURNING id, email, password_hash, full_name, phone, role, avatar_url, is_verified, background_check_passed, created_at, updated_at
`

type CreateUserParams struct {
	Email                 string `json:"email"`
	PasswordHash          string `json:"password_hash"`
	FullName              string `json:"full_name"`
	Phone                 string `json:"phone"`
	Role                  string `json:"role"`
	IsVerified            bool   `json:"is_verified"`
	BackgroundCheckPassed bool   `json:"background_check_passed"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Email,
		arg.PasswordHash,
		arg.FullName,
		arg.Phone,
		arg.Role,
		arg.IsVerified,
		arg.BackgroundCheckPassed,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.Phone,
		&i.Role,
		&i.AvatarUrl,
		&i.IsVerified,
		&i.BackgroundCheckPassed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one
SELECT id, email, password_hash, full_name, phone, role, avatar_url, is_verified, background_check_passed, created_at, updated_at FROM users
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.Phone,
		&i.Role,
		&i.AvatarUrl,
		&i.IsVerified,
		&i.BackgroundCheckPassed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, full_name, phone, role, avatar_url, is_verified, background_check_passed, created_at, updated_at FROM users
WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.Phone,
		&i.Role,
		&i.AvatarUrl,
		&i.IsVerified,
		&i.BackgroundCheckPassed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET
  full_name = COALESCE($1, full_name),
  phone = COALESCE($2, phone),
  avatar_url = COALESCE($3, avatar_url),
  updated_at = now()
WHERE id = $4
RETURNING id, email, password_hash, full_name, phone, role, avatar_url, is_verified, background_check_passed, created_at, updated_at
`

type UpdateUserParams struct {
	FullName  *string `json:"full_name"`
	Phone     *string `json:"phone"`
	AvatarUrl *string `json:"avatar_url"`
	ID        int64   `json:"id"`
}

// COALESCE rather than a blanket write: the profile form submits only the
// fields it shows, and an absent key must leave the column alone instead of
// blanking it.
func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.FullName,
		arg.Phone,
		arg.AvatarUrl,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.FullName,
		&i.Phone,
		&i.Role,
		&i.AvatarUrl,
		&i.IsVerified,
		&i.BackgroundCheckPassed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :exec
UPDATE users
SET password_hash = $2, updated_at = now()
WHERE id = $1
`

type UpdateUserPasswordParams struct {
	ID           int64  `json:"id"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error {
	_, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	return err
}
